KEY_REGEX = r"^[A-Za-z0-9._-]{16,4096}$"
KEY_PROFILE = "default"
MODEL_PREFIX = "byok/"
VERIFIED_AT = "2026-10-08"

MODEL_ENV_VARS = (
    "ANTHROPIC_MODEL",
    "ANTHROPIC_DEFAULT_OPUS_MODEL",
    "ANTHROPIC_DEFAULT_SONNET_MODEL",
    "ANTHROPIC_DEFAULT_HAIKU_MODEL",
    "ANTHROPIC_DEFAULT_FABLE_MODEL",
    "ANTHROPIC_SMALL_FAST_MODEL",
    "CLAUDE_CODE_SUBAGENT_MODEL",
)
ROUTING_MODE_ENV_VARS = (
    "CLAUDE_CODE_USE_BEDROCK",
    "CLAUDE_CODE_USE_VERTEX",
    "CLAUDE_CODE_USE_FOUNDRY",
)
CREDENTIAL_ENV_VARS = (
    "ANTHROPIC_API_KEY",
    "ANTHROPIC_AUTH_TOKEN",
    "CLAUDE_CODE_OAUTH_TOKEN",
    "CLAUDE_CODE_SESSION_KEY",
)

DOMESTIC_PRESETS = (
    {
        "id": "glm-intl",
        "family": "glm",
        "name": "GLM (Z.AI)",
        "region": "International",
        "base_url": "https://api.z.ai/api/anthropic",
        "models": ("glm-4.7", "glm-4.5-air"),
        "signup_url": "https://z.ai/manage-apikey/apikey-list",
        "docs_url": "https://docs.z.ai/scenario-example/develop-tools/claude",
        "price_note": "Paid. Uses your GLM Coding Plan allowance. Check your plan before running.",
        "region_note": "Use a Z.AI key here. A China Zhipu key belongs on the China endpoint.",
        "key_hint": "Paste your Z.AI API key",
        "no_key_status": 401,
    },
    {
        "id": "glm-cn",
        "family": "glm",
        "name": "GLM (Zhipu)",
        "region": "China",
        "base_url": "https://open.bigmodel.cn/api/anthropic",
        "models": ("glm-5.3", "glm-4.7"),
        "signup_url": "https://bigmodel.cn/usercenter/proj-mgmt/apikeys",
        "docs_url": "https://docs.bigmodel.cn/cn/guide/develop/claude",
        "models_docs_url": "https://docs.bigmodel.cn/cn/guide/develop/claude/introduction",
        "price_note": "Paid. Charges or coding-plan limits depend on your Zhipu account and model.",
        "region_note": "Use a China Zhipu key here. International Z.AI keys use the other endpoint.",
        "key_hint": "Paste your Zhipu API key",
        "no_key_status": 401,
    },
    {
        "id": "kimi-intl",
        "family": "kimi",
        "name": "Kimi (Moonshot)",
        "region": "International",
        "base_url": "https://api.moonshot.ai/anthropic",
        "models": ("kimi-k3", "kimi-k2.6"),
        "signup_url": "https://platform.kimi.ai/console/api-keys",
        "docs_url": "https://platform.kimi.ai/docs/guide/claude-code-kimi",
        "price_note": "Paid API usage from your Moonshot balance. A Kimi chat subscription is separate.",
        "region_note": "Use a key from the international API platform, not a Kimi Code subscription key.",
        "key_hint": "Paste your Moonshot API key",
        "no_key_status": 401,
    },
    {
        "id": "kimi-cn",
        "family": "kimi",
        "name": "Kimi (Moonshot)",
        "region": "China",
        "base_url": "https://api.moonshot.cn/anthropic",
        "models": ("kimi-k3", "kimi-k2.6"),
        "signup_url": "https://platform.kimi.com/console/api-keys",
        "docs_url": "https://platform.kimi.com/docs/guide/claude-code-kimi",
        "price_note": "Paid API usage from your Moonshot balance. A Kimi chat subscription is separate.",
        "region_note": "Use a key from the China API platform, not a Kimi Code subscription key.",
        "key_hint": "Paste your Moonshot API key",
        "no_key_status": 401,
    },
    {
        "id": "deepseek",
        "family": "deepseek",
        "name": "DeepSeek",
        "region": "International and China",
        "base_url": "https://api.deepseek.com/anthropic",
        "models": ("deepseek-flash", "deepseek-v4-pro"),
        "signup_url": "https://platform.deepseek.com/api_keys",
        "docs_url": "https://api-docs.deepseek.com/guides/anthropic_api/",
        "price_note": "Paid API usage. Flash and Pro have different prices. Check your balance before running.",
        "region_note": "DeepSeek documents one shared endpoint for international and China accounts.",
        "key_hint": "Paste your DeepSeek API key",
        "no_key_status": 401,
    },
    {
        "id": "qwen-intl",
        "family": "qwen",
        "name": "Qwen (DashScope)",
        "region": "International (Singapore)",
        "base_url": "https://dashscope-intl.aliyuncs.com/apps/anthropic",
        "models": ("qwen3-coder-plus", "qwen3.7-plus"),
        "signup_url": "https://www.alibabacloud.com/help/en/model-studio/get-api-key",
        "docs_url": "https://www.alibabacloud.com/help/en/model-studio/base-url",
        "models_docs_url": "https://www.alibabacloud.com/help/en/model-studio/anthropic-api-messages",
        "price_note": "Paid, pay as you go. Trial credits may expire. Coding Plan keys need a different endpoint.",
        "region_note": "Create a Model Studio key in Singapore. Beijing and Coding Plan keys do not work here.",
        "key_hint": "Paste your Singapore API key",
        "reject_key_prefixes": ("sk-sp-",),
        "no_key_status": 403,
    },
    {
        "id": "qwen-cn",
        "family": "qwen",
        "name": "Qwen (DashScope)",
        "region": "China (Beijing)",
        "base_url": "https://dashscope.aliyuncs.com/apps/anthropic",
        "models": ("qwen3-coder-plus", "qwen3.7-plus"),
        "signup_url": "https://www.alibabacloud.com/help/en/model-studio/get-api-key",
        "docs_url": "https://www.alibabacloud.com/help/en/model-studio/base-url",
        "models_docs_url": "https://www.alibabacloud.com/help/en/model-studio/anthropic-api-messages",
        "price_note": "Paid, pay as you go. Trial credits may expire. Coding Plan keys need a different endpoint.",
        "region_note": "Create a Model Studio key in Beijing. Singapore and Coding Plan keys do not work here.",
        "key_hint": "Paste your Beijing API key",
        "reject_key_prefixes": ("sk-sp-",),
        "no_key_status": 403,
    },
    {
        "id": "minimax-intl",
        "family": "minimax",
        "name": "MiniMax",
        "region": "International",
        "base_url": "https://api.minimax.io/anthropic",
        "models": ("MiniMax-M3", "MiniMax-M2.7"),
        "signup_url": "https://platform.minimax.io/user-center/basic-information/interface-key",
        "docs_url": "https://platform.minimax.io/docs/api-reference/text-anthropic-api",
        "region_docs_url": "https://platform.minimax.io/docs/guides/text-m3-function-call",
        "price_note": "Paid. API balance or M Plan resources are required. Check the price for your model.",
        "region_note": "Use a key from the international MiniMax platform. China keys use the China endpoint.",
        "key_hint": "Paste your MiniMax API key",
        "no_key_status": 401,
    },
    {
        "id": "minimax-cn",
        "family": "minimax",
        "name": "MiniMax",
        "region": "China",
        "base_url": "https://api.minimax.cn/anthropic",
        "models": ("MiniMax-M3", "MiniMax-M2.7"),
        "signup_url": "https://platform.minimax.cn/user-center/basic-information/interface-key",
        "docs_url": "https://platform.minimax.cn/docs/guides/quickstart-preparation",
        "models_docs_url": "https://platform.minimax.io/docs/api-reference/text-anthropic-api",
        "price_note": "Paid. API balance or M Plan resources are required. Check the price for your model.",
        "region_note": "Use a key from the China MiniMax platform. International keys use the other endpoint.",
        "key_hint": "Paste your MiniMax API key",
        "no_key_status": 401,
    },
)
